Add flyway for DB migrations (#7)
Use flyway for database migrations

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -2,8 +2,10 @@
 
 set -e
 
-command -v brew >/dev/null 2>&1 ||
-  { echo >&2 "Homebrew is required. Please install from https://brew.sh"; exit 1; }
+command -v brew >/dev/null 2>&1 || {
+  echo >&2 "Homebrew is required. Please install from https://brew.sh"
+  exit 1
+}
 
 R="\x1B[1;31m"
 G="\x1B[1;32m"
@@ -12,6 +14,10 @@ W="\x1B[0m"
 function output {
   echo -e "${R}${1}${W}"
 }
+
+# required homebrew programs
+command -v psql >/dev/null 2>&1 || { brew install postgresql; }
+command -v flyway >/dev/null 2>&1 || { brew install flyway; }
 
 case $SHELL in
   /bin/bash)
@@ -24,11 +30,13 @@ esac
 
 already_activated=`cat $profile | grep activate.sh | wc -c`
 
+# configure autoenv
 if [[ $already_activated -eq 0 ]]; then
   brew install autoenv
   echo "source $(brew --prefix autoenv)/activate.sh" >> $profile
 fi
 
+# configure virtualenv
 if [ ! -d ".venv" ]; then
   echo install virtualenv
   pip install virtualenv
@@ -36,11 +44,11 @@ if [ ! -d ".venv" ]; then
   echo "source .venv/bin/activate" > .env
   source .venv/bin/activate
 
-  pip install -r requirements.txt
+  pip install -qr requirements.txt
 
   echo
   echo Please run the following:
   output "source .venv/bin/activate"
 else
-  pip install -r requirements.txt
+  pip install -qr requirements.txt
 fi
